import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SideNav from '@/components/side-nav';
import Header from '@/components/header';
import SideMenu from '@/components/side-menu';
import Footer from '@/components/footer';
// import { ThemeProvider } from './helper/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* <ThemeProvider attribute="class" defaultTheme="dark"> */}
        <div className="bg-slate-600 sm:flex">
          <SideNav />
          <SideMenu />
          <Header />
          <main className="w-full px-6 pb-17 pt-4 font-rbtm">{children}</main>
        </div>
        <Footer />
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
