import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SideNav from '@/components/side-nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-slate-600 flex">
          <SideNav />
          <main className='rounded-xl m-2 bg-black-100 w-full p-6 lg:p-12 xl:p-20'>{children}</main>
        </div>
      </body>
    </html>
  );
}
